modLoader="kotlinforforge"
loaderVersion="[1,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/thebrightspark/Land-Manager/issues"

[[mods]]
    modId="landmanager"
    version="${file.jarVersion}"
    displayName="Land Manager"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/land-manager"
    #logoFile="banner.png"
    authors="bright_spark"
    description='''
    Manage custom sized areas of the world and allocate them to players!
    '''

[[dependencies.landmanager]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.landmanager]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
